### ISSUE TITLE
Kann hier jemand Willard einfügen für das Mod Development für das neue JTAC Gear?

### ISSUE THREAD

**Issue by ghost** [TaskForce47/tf47_jtac_gear#1]
Kann hier jemand Willard einfügen für das Mod Development für das neue JTAC Gear? Sollte das nicht möglich sein, dann bitte diese Repo closen und mich in Kenntnis setzen.

**Comment by phumberdroz** [comment]
lol lol lol lol nö. wäre cool wenn du seinen account nochmal posten kannst.

**Comment by ghost** [comment]
TheNiner sorry du model

**Comment by TheWillard** [comment]
ohne die 9

**Comment by TheWillard** [comment]
Danke sehr

**Comment by phumberdroz** [comment]
nicht @TheNiner ?

**Comment by phumberdroz** [comment]
ah perfekt .

**Comment by ghost** [comment]
psssht
